### ISSUE TITLE
undefined name problem when rename

### ISSUE THREAD

**Issue by zhangjinrui2718** [dataplane-app/dataplane#526]
in this situation : 
![image](https://user-images.githubusercontent.com/20435889/209895351-47223086-4490-4760-b0cb-1c6ab5684ff1.png)

when i drag a new python component into the canvas ，rename it and save , it shows the error like :
![image](https://user-images.githubusercontent.com/20435889/209895459-2025e99b-ba61-4919-92fe-fc81793ec9cd.png)

**Comment by saul-data** [comment]
We spotted that too, thanks for reporting. https://github.com/dataplane-app/dataplane/pull/524 Fix is on its way. The reason why this is breaking is because we are busy getting the folder structures ready for Github integration so pipelines can be stored as code. Each nodes needs to be unique which is linked to folders that also need to be unique for this to work. I should be able to release tonight.

**Comment by saul-data** [comment]
@zhangjinrui2718 This issue has been fixed as part of release https://github.com/dataplane-app/dataplane/releases/tag/v0.3.5 - please pull the latest and let me know if it works on your end.

**Comment by zhangjinrui2718** [comment]
its fixed in v0.3.5~

i will be glad to use github to manage my pipeline because of the complex pipelines.


by the way
i have some py-files shared by most components , now i copy them from one to another.
when these files changed, i need modify them one by one in every component
is there any graceful method to achieve it?

**Comment by saul-data** [comment]
@zhangjinrui2718 Sharing python code across nodes is becoming a popular request and I am busy looking into it. The best method right now is to package your python code into private pip packages and install via PIP on the workers. I will look into making this much easier with GUI inside the Dataplane platform. 

Here are others talking about it: https://github.com/dataplane-app/dataplane/discussions/532
